### ISSUE TITLE
[BUG] Downsampling Segmentation produces incorrectly scaled debug output images

### ISSUE THREAD

**Issue by nik-as** [MannLabs/scPortrait#131]
The mask overlay and image in `tileXX_Results_mask_matching.png` images that are generated during `project.segment()` of the following scPortrait project do not match in scale, see attached image.

```
project = Project(
    os.path.abspath(project_location),
    config_path="config.yml",
    overwrite=True,
    debug=True,
    segmentation_f=ShardedCytosolSegmentationDownsamplingCellpose,
    extraction_f=HDF5CellExtraction,
    featurization_f=CellFeaturizer,
    selection_f=LMDSelection,
)
```

config.yml:
```
name: "config scaling issue"
input_channels: 4
output_channels: 6
ShardedCytosolSegmentationDownsamplingCellpose:
    input_channels: 2
    output_masks: 2
    shard_size:  120000000 # maxmimum number of pixels per tile (add 6x6 to account for downsampling)
    overlap_px: 300
    nGPUs: 4
    chunk_size: 50 # chunk size for chunked HDF5 storage. is needed for correct caching and high performance reading. should be left at 50.
    threads: 3 # number of shards / tiles segmented at the same size. should be adapted to the maximum amount allowed by memory.
    cache: "."
    lower_quantile_normalization:   0.001
    upper_quantile_normalization:   0.999
    median_filter_size: 6 # Size in pixels
    nucleus_segmentation:
        model: "nuclei"
    cytosol_segmentation:
        model: "cyto2"
    chunk_size: 50
    filtering_threshold: 0.95
    downsampling_factor: 6
    smoothing_kernel_size: 7
    filter_status: False
multithreaded_filtering_match_nucleus_to_cytosol:
    filtering_threshold: 0.95
    cache: "."
    tile_size: 12000000
    overlap_px: 300
    threads: 38
    downsampling_factor: 6
```

<img width="237" alt="image" src="https://github.com/user-attachments/assets/09633462-a888-465b-a57e-776139311c49">
